### ISSUE TITLE
New type value `type: declaration` for 90th meeting of the CIPM

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-data-outcomes#7]
From [meeting-90.yml](https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-90.yml#L74-L81):

````
- dates:
  - '2001-10-12'
  subject: CIPM
  type: recommendation
  title: '"SI units" and "units of the SI"'
  identifier: 2001
  url: https://www.bipm.org/en/committees/ci/cipm/90-2001/resolution-
````

The encoded type is `recommendation`. But according to the
given url: https://www.bipm.org/en/committees/ci/cipm/90-2001/resolution-
the type should be `declaration` or `statement`.
